config/routes.rb
Employee::Application.routes.draw do
  resources :categories

  resources :downloads

  resources :reports  do
    get :date_report, :on=>:member
  end


  resources :districts

  resources :states

  resources :roles

  resources :users do
    get :profile, :on=>:member
    get :update_profile,:on=>:member
    put :profile_update,:on=>:member
    get :change_password,:on=>:member
    put :import,:on=>:collection
    get :upload,:on=>:collection
    get :approve, :on=>:member
    get :reset, :on=>:member
  end

  resources :user_sessions
  resources :homes

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => "user_sessions#new"


  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.require_password_confirmation= false
    c.validate_password_field= false
  end


  validates :name, :presence => true, :length => {:maximum => 100}
  validates :mobile_number, :presence => true, :length => {:maximum => 10}
  validates :email, :presence => true, :uniqueness => true

  #Relations
  has_many :assignments
  has_many :roles, :through => :assignments
  belongs_to :state
  belongs_to :district

  has_many :reports

  #Roles
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  #Recent and Search
  class << self
    def recent
      order('id DESC').limit(4)
    end

    def search(query)
      if query
        where({:name.matches => "%#{query}%"} | {:mobile_number.matches => "%#{query}%"} | {:email.matches => "%#{query}%"}) #from meta_where gem
      else
        scoped
      end
    end
    def employee_users
      joins([:roles]).where(:roles => {:name => %w(employee)})
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "application", :except => [:show]
  before_filter :require_user, :recent_items
  filter_access_to :all

  def index
    @users = User.search(params[:search]).paginate(:page => page, :per_page => per_page) if has_any_role?(:admin, :manager)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    @user.password=params[:user][:email]


    respond_to do |format|
      if @user.save
        #send Mail
        UserMailer.welcome_email(@user).deliver

        format.html { redirect_to(users_url, :notice => 'User was successfully created.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_path, :notice => 'User was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml { head :ok }
    end
  end

  def profile
    @user = User.find(params[:id])
  end

  def update_profile
    @user = User.find(params[:id])
  end

  def profile_update
    @user = current_user
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(profile_user_path(current_user), :notice => 'Profile Updated Successfully.') }
        format.xml { head :ok }
      else
        format.html { render :action => "profile_update" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def change_password
    @user = current_user
  end

  def password_change
    @user = current_user
    return flash.now[:error] = "Current password is Wrong/Blank" unless @user.valid_password? params[:old_password]
    if params[:password] == params[:password_confirmation] && !params[:password_confirmation].blank?
      @user.password = params[:password]
      if @user.save
        flash.now[:notice] = "Password Changed Successfully."
        #redirect_to profile_user_path(current_user)
      else
        flash.now[:error]= "Password not changed"
      end
    else
      flash.now[:error] = "New Password mismatch"
      @old_password = params[:old_password]
    end
  end

  def upload
    render
  end

  def import
    require 'csv'
    csv_file = params[:file]
    n=0
    CSV.new(csv_file.tempfile, :col_sep => ",").each do |row|
      user = User.create do |u|
        u.name =row[0]
        u.email = row[1]
        u.password = row[1]
        u.mobile_number = row[2]
        district=District.find_by_name(row[3].strip)
        u.district_id =district.id
        u.state_id = 1
      end
      if user.save
        Assignment.create(:user_id => user.id, :role_id => 3, :created_at => Time.now, :updated_at => Time.now)
      end
      n = n + 1
    end
    flash[:notice]= "#{n} Users are imported successfully"
    respond_to do |format|
      format.html { redirect_to(users_path) }
      format.xml { head :ok }
    end
  end
  def approve
    @user = User.find(params[:id])
    @user.update_attribute('status', @user.status ? false : true)
    respond_to do |format|
      format.js
    end
  end
  def reset
    @user = User.find(params[:id])
    @user.password = @user.email

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_path, :notice => 'User password is Reset.') }
      else
        format.html { redirect_to(users_path, :error => 'User password is Not Reset.') }
      end
    end

  end

    ###################################################
  private
  def recent_items
    @recent = User.recent
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@user, :validate => true) do |f| %>
      <fieldset>
        <%= f.error_messages %>
        <%= f.input :name, :label=>"Full Name", :placeholder=>"Full Name" %>
        <%= f.input :email, :label=>"Email",:placeholder=>"user@example.com"%>
        <%= f.input :father_name, :label=>"Father Name",:placeholder=>"Father Name" %>
        <%= f.input :gender, :collection => [:Male, :Female],:prompt=>"Select Gender" %>
        <%= f.input :dob, :label=>"DOB", :as => :date, :start_year => Date.today.year,
                    :end_year => Date.today.year - 60,
                    :order => [:day, :month, :year] %>
        <%= f.input :address1, :label=>"Address", :placeholder=>"Address" %>
        <%= f.input :address2, :label=>"Address",:placeholder=>"Address" %>
        <%= f.input :place, :label=>"Place",:placeholder=>"Village / Town Name" %>
        <%= f.input :pin, :label=>"PIN", :placeholder=>"PIN code Must be 6 Digits" %>
        <%= f.input :mobile_number, :label=>"Mobile", :placeholder=>"Mobile Number Must be 10 Digits" %>
        <%= f.input :phone_number, :label=>"Land Phone",:placeholder=>"Phone Number" %>

        <%= f.association :state, :prompt=>"Select State"%>
        <%= f.association :district,:collection => District.all(:order => 'name'), :prompt => "Select District"%>
        <%= f.association :roles,:label_method => lambda { |role| "#{role.name.titleize} " } %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/users/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent Users</h3>
    <% if @recent.blank? %>
        No Users Added Yet...
    <% else %>
        <% for user in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to user.name, user_path(user), :class=>'usuallink tipTipRight',:rel=>"facebox",:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="/users">
        View all Users
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/users/approve.js.erb
$("#status_<%=@user.id%>").html("<%=escape_javascript(link_to @user.status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_user_path,:remote=>true)%>");

app/views/users/change_password.html.erb
<% title "VEDAVAAG | Users" %>
<h3>Users | Profile | Change Password</h3>
<div class="help_text">
  Area for Change the Password. <br/>
</div>
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= form_tag '/users/password_change', :remote => true do %>
      <fieldset>
        <table>
          <tr>
            <td><label>Current Password<em>*</em></label></td>
            <td><%= password_field_tag 'old_password', @old_password, :class => 'formTextBox tipTipRight', :title => "Enter Old Password" %></td>
          </tr>
          <tr>
            <td><label>New Password<em>*</em></label></td>
            <td><%= password_field_tag 'password', '', :class => 'formTextBox tipTipRight', :title => "Enter New Password.<br/>For more secure use combination of Characters and Numbers" %></td>
          </tr>
          <tr>
            <td><label>Confirm New Password<em>*</em></label></td>
            <td><%= password_field_tag 'password_confirmation', '', :class => 'formTextBox tipTipRight', :title => "Confirm New Password." %></td>
          </tr>
          <tr>&nbsp;</tr>
          <tr>
            <td colspan="2" align="center"><%= submit_tag 'Change Password', :class => "btnEdit" %></td>
          </tr>
        </table>
      </fieldset>
  <% end %>
  <br/>
  <%= link_to content_tag(:span, 'Back to Profile'), profile_user_path(current_user), :class => 'btn-blue' %>
  <br/>
</div>

app/views/users/edit.html.erb
<% title "VEDAVAAG | Users " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | Users','Update User') %>
<% end %>
<%= render 'form',:heading => 'Update User' %>
<div class="link_buttons">
  <%=link_to_all(users_path)%>
</div>

app/views/users/index.html.erb
<% title "VEDAVAAG | Users" %>
<h3>VEDAAAG | Users | Manage Users</h3>

<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Users. <br/>
  Along with creating, managing Users for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New User'), new_user_path, :class => 'btn-blue' %>
  <%#link_to content_tag(:span, 'Export'), export_users_path, :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-yellow' %>
</div>

<% if @users.blank? %>
    <div class="error_msg">
      OOPS!.. No Users are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @users %>
        </td>
      </tr>
    </table>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Status?</th>
        <th>Name</th>
        <th>Email</th>
        <th>State</th>
        <th>District</th>
        <th>Mobile</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @users.each do |user| %>
          <tr>
            <td><%= i %></td>
            <td><%= link_to_active(user, approve_user_path(user)) %></td>
            <td><%= highlight(user.name, params[:search]) %></td>
            <td><%= highlight(user.email,params[:search]) %></td>
            <td><%= user.state_id? ? user.state.name : 'N.A' %></td>
            <td><%= user.district_id? ? user.district.name : 'N.A' %></td>
            <td><%= highlight(user.mobile_number,params[:search]) %></td>
            <td><%= get_role(user) %></td>
            <td>
              <%= link_for_show_pop(user) %>
              <%= link_for_edit(edit_user_path(user)) %>
              <%= link_for_reset(reset_user_path(user)) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @users %> <%= will_paginate @users, :container => false %>
    </div>
<% end %>

app/views/users/new.html.erb
<% title "VEDAVAAG | Users " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | Users','Create User') %>
<% end %>
<%= render 'form',:heading => 'Create New User' %>
<div class="link_buttons">
  <%=link_to_all(users_path)%>
</div>

app/views/users/password_change.js.erb
$('#flash_messages').html('<%=escape_javascript(render :partial=>'common/flash_message')%>');

app/views/users/profile.html.erb
<% title "SECC | User" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Users | Profile | View Profile</h3>

      <div class="help_text">
        Area for Profile Details. <br/>
        User can Update their Name, Mobile Numbers Only.
      </div>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Email</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th width="20%">Name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th width="20%">Father Name</th>
          <td><%= @user.father_name %></td>
        </tr>
        <tr>
          <th width="20%">Date of Birth</th>
          <td><%= @user.dob? ? @user.dob.strftime("%d-%b-%Y") : 'N.A' %></td>
        </tr>
        <tr>
          <th width="20%">Address</th>
          <td><%= @user.address1 %></td>
        </tr>
        <tr>
          <th width="20%">Place</th>
          <td><%= @user.place %></td>
        </tr>
        <tr>
          <th width="20%">PIN</th>
          <td><%= @user.pin %></td>
        </tr>
        <tr>
          <th width="20%">Mobile</th>
          <td><%= @user.mobile_number %></td>
        </tr>
            <tr>
              <th width="20%">State</th>
              <td><%= @user.state_id? ? @user.state.name : 'N.A' %></td>
            </tr>
            <tr>
              <th width="20%">District</th>
              <td><%= @user.district_id? ? @user.district.name : 'N.A' %></td>
            </tr>
      </table>
    </div>
  </div>
  <br/>
  <%= link_to content_tag(:span, 'Update Profile'), update_profile_user_path(current_user), :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Change Password'), change_password_user_path(current_user), :class => 'btn-blue' %>
</div>

app/views/users/show.html.erb
<% title "VEDAVAAG | User" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Users | View User Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Email</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th width="20%">Name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th width="20%">Mobile</th>
          <td><%= @user.mobile_number %></td>
        </tr>
        <tr>
          <th width="20%">State</th>
          <td><%# @user.user_profile.state_id? ? @user.user_profile.state.name : 'N.A' %></td>
        </tr>
        <tr>
          <th width="20%">District</th>
          <td><%# @user.user_profile.district_id? ? @user.user_profile.district.name : 'N.A' %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/users/update_profile.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@user, :validate => true,:url=>url_for(:action=>:profile_update)) do |f| %>
      <fieldset>
        <%= f.error_messages %>
        <%= f.input :email,:label=>"Email", :disabled => true%>
        <%= f.input :name, :label=>"Name", :placeholder=>"Full Name" %>
        <%= f.input :father_name, :label=>"Father Name",:placeholder=>"Father Name" %>
        <%= f.input :gender, :collection => [:Male, :Female],:prompt=>"Select Gender" %>
        <%= f.input :dob, :label=>"DOB", :as => :date, :start_year => Date.today.year,
                    :end_year => Date.today.year - 60,
                    :order => [:day, :month, :year] %>
        <%= f.input :address1, :label=>"Address", :placeholder=>"Address" %>
        <%= f.input :address2, :label=>"Address",:placeholder=>"Address" %>
        <%= f.input :place, :label=>"Place",:placeholder=>"Village / Town Name" %>
        <%= f.input :pin, :label=>"PIN", :placeholder=>"PIN code Must be 6 Digits" %>
        <%= f.input :mobile_number, :label=>"Mobile", :placeholder=>"Mobile Number Must be 10 Digits" %>
        <%= f.input :phone_number, :label=>"Land Phone",:placeholder=>"Phone Number" %>
        <%= f.submit 'Update Profile', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
  <br/>
  <%= link_to content_tag(:span, 'Back to Profile'), profile_user_path(current_user), :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Change Password'), change_password_user_path(current_user), :class => 'btn-blue' %>
  <br/>
</div>

app/views/users/upload.html.erb
<h4>Please Select the Transactions File</h4>
<%= form_tag import_users_path, :multipart => true do  -%>
    <table class="tablesorter1" align="center">
      <tr>
        <td>
          <label for="vle_user">
            Select a CSV File :
          </label>
        </td>
        <td>
          <%= file_field_tag :file,:id=>"statename" -%>
          <script type="text/javascript">
              var statename = new LiveValidation('statename', {
                  onlyOnSubmit: true
              });
              statename.add(Validate.Presence)
          </script>
        </td>
      </tr>
      <tr>
        <td colspan='2' align="right">
          <%= submit_tag 'Submit' ,:disable_with=>'Please wait...'-%>
        </td>
      </tr>
    </table>
<% end -%>
<style type="text/css">
    table.tablesorter1 {
        border-collapse: collapse;
        border: 1px solid #CDCDCD;
        text-align: center;
    }
    table.tablesorter1 td, table.tablesorter1 th{
        border-collapse: collapse;
        border: 1px solid #CDCDCD;
    }

</style>