config/routes.rb
Employee::Application.routes.draw do
  resources :categories

  resources :downloads

  resources :reports  do
    get :date_report, :on=>:member
  end


  resources :districts

  resources :states

  resources :roles

  resources :users do
    get :profile, :on=>:member
    get :update_profile,:on=>:member
    put :profile_update,:on=>:member
    get :change_password,:on=>:member
    put :import,:on=>:collection
    get :upload,:on=>:collection
    get :approve, :on=>:member
    get :reset, :on=>:member
  end

  resources :user_sessions
  resources :homes

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => "user_sessions#new"


  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/state.rb
class State < ActiveRecord::Base
  #Relations
  has_many :districts

  #validations
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 100}

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        where(:name.matches => "%#{query}%") #from meta_where gem
      else
        scoped
      end
    end
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  layout "application", :except => [:show, :edit]
  before_filter  :require_user,:recent_items
  filter_access_to :all

  def index
    @states = State.search(params[:search]) if has_any_role?(:admin,:manager)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @states }
    end
  end

  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @state }
    end
  end

  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @state }
    end
  end

  def edit
    @state = State.find(params[:id])
  end

  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to(states_url, :notice => 'State was successfully created.') }
        format.xml  { render :xml => @state, :status => :created, :location => @state }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to(@state, :notice => 'State was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to(states_url) }
      format.xml  { head :ok }
    end
  end
  private
  def recent_items
    @recent = State.recent
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@state, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name,:placeholder=>"Enter State Name" %>
        <%= f.input :description %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/states/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent States</h3>
    <% if @recent.blank? %>
        No States Added Yet...
    <% else %>
        <% for state in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to state.name.titleize, state_path(state), :class=>'usuallink tipTipRight',:rel=>"facebox",:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="/states">
        View all States
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<% title "VEDAVAAG | States" %>
<h3>VEDAVAAG | States | Manage States</h3>
<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing States. <br/>
  Along with creating, managing  States for Application.
</div>
<%#link_to ((t :create_new) + ' ' + (t :states) ), "#", :class=>'usuallink bold_text', :id=>'add_new' %>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New State'), new_state_path, :class => 'btn-blue' if permitted_to? :create %>
  <%# link_to content_tag(:span, 'Export'), export_states_path, :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-yellow' %>
</div>
<!--
<div id="new_form">
  <%#render 'form' %>
</div>
-->
<% if @states.blank? %>
    <div class="error_msg">
      OOPS!.. No States are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>SNo</th>
        <th>Name</th>
        <th>Districts</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @states.each do |state| %>
          <tr>
            <td><%= i %></td>
            <td><%= highlight(state.name.titleize,params[:search]) %></td>
            <td><%= link_to state.districts.size, districts_path, :class => 'tipTipRight', :title => associated_names(state.districts) %></td>
            <td>
              <%= link_for_show_pop(state) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/states/new.html.erb
<% title "VEDAVAAG | States " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | States','Create State') %>
<% end %>
<div class="help_text_caution">
  FURTHER MODIFICATION WILL NOT POSSIBLE AFTER SUBMITTING THE FORM.
</div>
<%= render 'form',:heading => 'Create New State' %>
<div class="link_buttons">
  <%=link_to_all(states_path)%>
</div>

app/views/states/show.html.erb
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>States | View State Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Name</th>
          <td><%= @state.name %></td>
        </tr>
        <tr>
          <th width="20%">Description</th>
          <td><%= @state.description %></td>
        </tr>
      </table>
    </div>
  </div>
</div>