config/routes.rb
Employee::Application.routes.draw do
  resources :categories

  resources :downloads

  resources :reports  do
    get :date_report, :on=>:member
  end


  resources :districts

  resources :states

  resources :roles

  resources :users do
    get :profile, :on=>:member
    get :update_profile,:on=>:member
    put :profile_update,:on=>:member
    get :change_password,:on=>:member
    put :import,:on=>:collection
    get :upload,:on=>:collection
    get :approve, :on=>:member
    get :reset, :on=>:member
  end

  resources :user_sessions
  resources :homes

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => "user_sessions#new"


  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/category.rb
class Category < ActiveRecord::Base

  #validation
  validates :name, :presence => true, :length => {:maximum => 100}

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        where(:name.matches => "%#{query}%") #from meta_where gem
      else
        scoped
      end
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "application", :except => [:show, :edit]
  before_filter  :require_user,:recent_items
  filter_access_to :all

  def index
    @categories = Category.search(params[:search]) if has_any_role?(:admin,:manager)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(categories_url, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
  private
  def recent_items
    @recent = Category.recent
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@category, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name,:placeholder=>"Enter Category Name" %>
        <%= f.input :description %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/categories/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent Categories</h3>
    <% if @recent.blank? %>
        No Categories Added Yet...
    <% else %>
        <% for category in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to category.name, category_path(category), :class=>'usuallink tipTipRight',:rel=>"facebox",:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="/categories">
        View all Categories
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% title "VEDAVAAG | Categories" %>
<h3>VEDAVAAG | Categories | Manage Categories</h3>
<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Categories. <br/>
  Along with creating, managing  Categories for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New Category'), new_category_path, :class => 'btn-blue' if permitted_to? :create %>
  <%= link_to content_tag(:span, 'Home'), homes_url, :class => 'btn-yellow' %>
</div>

<% if @categories.blank? %>
    <div class="error_msg">
      OOPS!.. No Categories are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>SNo</th>
        <th>Name</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @categories.each do |category| %>
          <tr>
            <td><%= i %></td>
            <td><%= highlight(category.name,params[:search]) %></td>
            <td><%= category.description %></td>
            <td>
              <%= link_for_show_pop(category) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/categories/new.html.erb
<% title "VEDAVAAG | Categories " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | States','Create Category') %>
<% end %>
<div class="help_text_caution">
  FURTHER MODIFICATION WILL NOT POSSIBLE AFTER SUBMITTING THE FORM.
</div>
<%= render 'form',:heading => 'Create New Category' %>
<div class="link_buttons">
  <%=link_to_all(categories_path)%>
</div>

app/views/categories/show.html.erb
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Categories | View Category Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Name</th>
          <td><%= @category.name %></td>
        </tr>
        <tr>
          <th width="20%">Description</th>
          <td><%= @category.description %></td>
        </tr>
      </table>
    </div>
  </div>
</div>